### ISSUE TITLE
Add PF unchained ( it's on the paizo prd!)

### ISSUE THREAD

**Issue by Oboema** [devonjones/PathfinderOpenReference#102]
At long last, paizo added some of their more recent books to their online prd! See e.g. http://paizo.com/pathfinderRPG/prd/unchained/classes/index.html
Could you re-rip the data and deploy it in the app?

Love the masterwork tools, keep it up :)

**Comment by devonjones** [comment]
Done, sorry it took so long, had another project blocking my time.
